apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskpg.fullname" . }}-postgres
  labels:
    {{- include "flaskpg.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.postgres.service.clusterIP }}
  selector:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
