apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: {{ .Values.postgres.containerPort }}
      name: postgres
  clusterIP: None
  selector:
    app: postgres
